# Generated by Django 3.1.6 on 2021-02-16 18:43

from django.db import migrations, models
import main_gusto.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to=main_gusto.models.Category.get_file_name),
        ),
    ]
