# Generated by Django 3.1.6 on 2021-02-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0004_auto_20210220_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='category',
        ),
    ]
