# Generated by Django 3.1.6 on 2021-03-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0007_adress_cafeinfo_message_openinghours_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeinfo',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
